export enum StringConstants {
  HTML = 'htmlcssjavascript',
  ANGULAR = 'angular',
  REACT = 'react',
  ASP = 'aspdotnetcore',
  RESTFUL = 'restful',
  ENTITY = 'entityframework',
  GIT = 'git',
  DOCKER = 'docker',
  JENKINS = 'jenkins',
  AZURE = 'azure',
  SPOKEN = 'spoken',
  COMM = 'communication',
  APTI = 'aptitude',
  NAME = 'name',
  ID = 'associateid',
  SKILL = 'skill',
}
